import type { Category, Tool } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'content',
    title: { ar: 'صناعة المحتوى', en: 'Content Creation' },
    icon: '📝',
  },
  {
    id: 'visuals',
    title: { ar: 'المرئيات', en: 'Visuals' },
    icon: '🎨',
  },
  {
    id: 'productivity',
    title: { ar: 'الإنتاجية', en: 'Productivity' },
    icon: '🚀',
  },
  {
    id: 'development',
    title: { ar: 'التطوير', en: 'Development' },
    icon: '💻',
  },
];

export const TOOLS: Tool[] = [
  // Content Creation
  {
    id: 'text',
    category: 'content',
    title: { ar: 'كاتب النصوص', en: 'Text Writer' },
    description: { ar: 'أنشئ نصوصًا إبداعية لأي غرض.', en: 'Generate creative text for any purpose.' },
    icon: '✍️',
    inputLabel: { ar: 'ما هي فكرة النص؟', en: 'What is the text idea?' },
    placeholder: { ar: 'مثال: اكتب قصة قصيرة عن روبوت...', en: 'e.g., Write a short story about a robot...' },
    loadingText: { ar: 'جاري كتابة النص...', en: 'Writing text...' },
    inputType: 'text',
  },
  {
    id: 'long_video_script',
    category: 'content',
    title: { ar: 'كاتب سكريبت فيديو طويل', en: 'Long Video Scripter' },
    description: { ar: 'إنشاء سكريبتات مفصلة لفيديوهات يوتيوب.', en: 'Create detailed scripts for YouTube videos.' },
    icon: '🎬',
    inputLabel: { ar: 'ما هو موضوع الفيديو؟', en: 'What is the video topic?' },
    placeholder: { ar: 'مثال: أفضل 5 وجهات سياحية في عام 2024', en: 'e.g., Top 5 travel destinations in 2024' },
    loadingText: { ar: 'جاري كتابة السكريبت...', en: 'Writing script...' },
    inputType: 'text',
  },
  {
    id: 'short_video_script',
    category: 'content',
    title: { ar: 'كاتب سكريبت فيديو قصير', en: 'Short Video Scripter' },
    description: { ar: 'أفكار وسكريبتات سريعة لفيديوهات تيك توك وريلز.', en: 'Quick ideas and scripts for TikTok & Reels.' },
    icon: '📱',
    inputLabel: { ar: 'ما هي فكرة الفيديو القصير؟', en: 'What is the short video idea?' },
    placeholder: { ar: 'مثال: 3 نصائح سريعة لزيادة الإنتاجية', en: 'e.g., 3 quick tips for productivity' },
    loadingText: { ar: 'جاري كتابة السكريبت...', en: 'Writing script...' },
    inputType: 'text',
  },
   {
    id: 'email',
    category: 'content',
    title: { ar: 'كاتب البريد الإلكتروني', en: 'Email Writer' },
    description: { ar: 'صياغة رسائل بريد إلكتروني احترافية بسرعة.', en: 'Draft professional emails quickly.' },
    icon: '📧',
    inputLabel: { ar: 'ما هو موضوع البريد الإلكتروني؟', en: 'What is the email about?' },
    placeholder: { ar: 'مثال: طلب اجتماع لمناقشة المشروع الجديد', en: 'e.g., Request a meeting to discuss the new project' },
    loadingText: { ar: 'جاري كتابة البريد...', en: 'Writing email...' },
    inputType: 'text',
  },

  // Visuals
  {
    id: 'image',
    category: 'visuals',
    title: { ar: 'مولد الصور', en: 'Image Generator' },
    description: { ar: 'حوّل أفكارك إلى صور مذهلة.', en: 'Turn your ideas into stunning images.' },
    icon: '🖼️',
    inputLabel: { ar: 'صف الصورة التي تريد إنشاءها', en: 'Describe the image you want to create' },
    placeholder: { ar: 'مثال: رائد فضاء يركب حصانًا على المريخ', en: 'e.g., An astronaut riding a horse on Mars' },
    loadingText: { ar: 'جاري إنشاء الصورة...', en: 'Generating image...' },
    inputType: 'text',
  },
  {
    id: 'image_bg_remover',
    category: 'visuals',
    title: { ar: 'مزيل خلفية الصور', en: 'Image BG Remover' },
    description: { ar: 'إزالة خلفية أي صورة بنقرة واحدة.', en: 'Remove the background of any image with one click.' },
    icon: '✨',
    inputLabel: { ar: 'ارفع صورة لإزالة خلفيتها', en: 'Upload an image to remove its background' },
    placeholder: { ar: '', en: '' },
    loadingText: { ar: 'جاري إزالة الخلفية...', en: 'Removing background...' },
    inputType: 'image',
  },
  {
    id: 'image_prompt_extractor',
    category: 'visuals',
    title: { ar: 'مستخرج أوامر الصور', en: 'Image Prompt Extractor' },
    description: { ar: 'احصل على وصف دقيق لأي صورة لاستخدامه كأمر.', en: 'Get a detailed description of any image to use as a prompt.' },
    icon: '🔍',
    inputLabel: { ar: 'ارفع صورة لاستخراج الوصف', en: 'Upload an image to extract its description' },
    placeholder: { ar: '', en: '' },
    loadingText: { ar: 'جاري تحليل الصورة...', en: 'Analyzing image...' },
    inputType: 'image',
  },
  {
    id: 'video_bg_remover',
    category: 'visuals',
    title: { ar: 'مزيل خلفية الفيديو', en: 'Video BG Remover' },
    description: { ar: 'إزالة خلفية الفيديو بسهولة ودقة.', en: 'Remove video backgrounds easily and accurately.' },
    icon: '🎥',
    inputLabel: { ar: 'ارفع فيديو لإزالة خلفيته', en: 'Upload a video to remove its background' },
    placeholder: { ar: '', en: '' },
    loadingText: { ar: 'جاري معالجة الفيديو...', en: 'Processing video...' },
    inputType: 'file', // or video? file is more generic
    disabled: true,
  },

  // Productivity
  {
    id: 'summary',
    category: 'productivity',
    title: { ar: 'تلخيص النصوص', en: 'Text Summarizer' },
    description: { ar: 'لخص المقالات الطويلة في نقاط موجزة.', en: 'Summarize long articles into brief points.' },
    icon: '📚',
    inputLabel: { ar: 'الصق النص هنا لتلخيصه', en: 'Paste the text to summarize here' },
    placeholder: { ar: 'أدخل النص الطويل...', en: 'Enter the long text...' },
    loadingText: { ar: 'جاري التلخيص...', en: 'Summarizing...' },
    inputType: 'text',
  },
  {
    id: 'translate',
    category: 'productivity',
    title: { ar: 'مترجم', en: 'Translator' },
    description: { ar: 'ترجمة دقيقة بين العربية والإنجليزية.', en: 'Accurate translation between Arabic and English.' },
    icon: '🌐',
    inputLabel: { ar: 'أدخل النص للترجمة', en: 'Enter text to translate' },
    placeholder: { ar: 'مرحباً بالعالم', en: 'Hello, World' },
    loadingText: { ar: 'جاري الترجمة...', en: 'Translating...' },
    inputType: 'text',
  },
  {
    id: 'video_text_extractor',
    category: 'productivity',
    title: { ar: 'مستخرج النصوص من الفيديو', en: 'Video Text Extractor' },
    description: { ar: 'استخرج النص الصوتي من ملف فيديو أو رابط.', en: 'Extract spoken text from a video file or link.' },
    icon: '🗣️',
    inputLabel: { ar: 'ارفع ملف فيديو أو الصق رابطًا', en: 'Upload a video file or paste a link' },
    placeholder: { ar: 'https://example.com/video.mp4', en: 'https://example.com/video.mp4' },
    loadingText: { ar: 'جاري تحليل الفيديو...', en: 'Analyzing video...' },
    inputType: 'file',
  },
  {
    id: 'video_downloader',
    category: 'productivity',
    title: { ar: 'تنزيل الفيديوهات', en: 'Video Downloader' },
    description: { ar: 'تنزيل الفيديوهات من المنصات الشهيرة.', en: 'Download videos from popular platforms.' },
    icon: '💾',
    inputLabel: { ar: 'الصق رابط الفيديو', en: 'Paste the video link' },
    placeholder: { ar: 'https://...', en: 'https://...' },
    loadingText: { ar: 'جاري التنزيل...', en: 'Downloading...' },
    inputType: 'text',
    disabled: true,
  },
  {
    id: 'file_converter',
    category: 'productivity',
    title: { ar: 'محول الملفات', en: 'File Converter' },
    description: { ar: 'تحويل الملفات بين الصيغ المختلفة (صور، مستندات).', en: 'Convert files between different formats (images, docs).' },
    icon: '🔄',
    inputLabel: { ar: 'ارفع ملفًا لتحويله', en: 'Upload a file to convert' },
    placeholder: { ar: '', en: '' },
    loadingText: { ar: 'جاري التحويل...', en: 'Converting...' },
    inputType: 'file',
    disabled: true,
  },
   {
    id: 'file_compressor',
    category: 'productivity',
    title: { ar: 'ضاغط الملفات', en: 'File Compressor' },
    description: { ar: 'تقليل حجم الملفات مع الحفاظ على الجودة.', en: 'Reduce file size while maintaining quality.' },
    icon: '📦',
    inputLabel: { ar: 'ارفع ملفًا لضغطه', en: 'Upload a file to compress' },
    placeholder: { ar: '', en: '' },
    loadingText: { ar: 'جاري الضغط...', en: 'Compressing...' },
    inputType: 'file',
    disabled: true,
  },

  // Development
  {
    id: 'code',
    category: 'development',
    title: { ar: 'كاتب الأكواد', en: 'Code Writer' },
    description: { ar: 'إنشاء أكواد برمجية لأي مهمة وفي أي لغة.', en: 'Generate code snippets for any task in any language.' },
    icon: '👨‍💻',
    inputLabel: { ar: 'صف الكود الذي تحتاجه', en: 'Describe the code you need' },
    placeholder: { ar: 'مثال: دالة بلغة بايثون لحساب المتوسط الحسابي', en: 'e.g., A Python function to calculate the average' },
    loadingText: { ar: 'جاري كتابة الكود...', en: 'Writing code...' },
    inputType: 'text',
  },
];